export { default as FilesIcon } from './files.svg'
export { default as TailwindIcon } from './tailwind.svg'
export { default as LinkIcon } from './link.svg'
export { default as LightningIcon } from './lightning.svg'
export { default as GlobeIcon } from './globe.svg'
export { default as PictureIcon } from './picture.svg'
export { default as CodeIcon } from './code.svg'
export { default as BrushIcon } from './brush.svg'
export { default as DropperIcon } from './dropper.svg'
export { default as StarsIcon } from './stars.svg'
export { default as FormulaIcon } from './formula.svg'
export { default as WarningIcon } from './warning.svg'
export { default as ChevronRightIcon } from './chevron-right.svg'
export { default as BoxIcon } from './box.svg'
export { default as GearIcon } from './gear.svg'
export { default as RowsIcon } from './rows.svg'
export { default as CardsIcon } from './cards.svg'
export { default as OneIcon } from './one.svg'
export { default as CloudIcon } from './cloud.svg'
export { default as TableIcon } from './table.svg'
export { default as FileIcon } from './file.svg'
export { default as NewsletterIcon } from './newsletter.svg'
export { default as ArrowRightIcon } from './arrow-right.svg'
export { default as SwitchIcon } from './switch.svg'
export { default as DiagramIcon } from './diagram.svg'
export { default as FolderTreeIcon } from './folder-tree.svg'
export { default as IdCardIcon } from './id-card.svg'
export { default as NextraLogo } from './nextra.svg'
export { default as DiscordIcon } from "./discord.svg"
export { default as GitHubIcon } from "./github.svg"
export { default as GraphQLLogo } from "./graphql.svg"
export { default as GraphQLWordmarkLogo } from "./graphql-wordmark.svg"
export { default as MagnifyingGlassIcon } from "./magnifying-glass.svg"
export { default as NPMIcon } from "./npm.svg"
export { default as RubyGemsIcon } from "./rubygems.svg"
export { default as StackOverflowIcon } from "./stackoverflow.svg"
export { default as StarIcon } from "./star.svg"
export { default as TwitterIcon } from "./twitter.svg"
export { default as LinkedInIcon } from "./linkedin.svg"
export { default as YouTubeIcon } from "./youtube.svg"
export { default as FacebookIcon } from "./facebook.svg"
export { default as Facebook2Icon } from "./facebook2.svg"
export { default as InstagramIcon } from "./instagram.svg"
export { default as HamburgerIcon } from "./hamburger.svg"
export { default as CrossIcon } from "./cross.svg"
export { default as ChevronLeftIcon } from "./chevron-left.svg"
export { default as GoogleCalendarIcon } from "./google-calendar.svg"
export { default as FileTextIcon } from "./file-text.svg"
export { default as RedditIcon } from "./reddit.svg"
export { default as ReactifluxIcon } from "./reactiflux.svg"
export { default as FreenodeIcon } from "./freenode.svg"
export { default as StellateIcon } from "./stellate.svg"
export { default as ChillicreamIcon } from "./chillicream.svg"
export { default as ApolloIcon } from "./apollo.svg"
export { default as GraphileIcon } from "./graphile.svg"
export { default as TextIcon } from "./text.svg"
export { default as LocationIcon } from "./location.svg"
export { default as ClockIcon } from "./clock.svg"
export { default as GraphQLConf } from "./graphql-conf.svg"
export { default as HostedByGraphQLFoundation } from "./hosted-by-graphql-foundation.svg"
export { default as CalendarIcon } from "./calendar.svg"
export { default as CheckIcon } from "./check.svg"
export { default as AroundIcon } from "./around.svg"
export { default as BusIcon } from "./bus.svg"
export { default as ParkingIcon } from "./parking.svg"
export { default as TrainIcon } from "./train.svg"
export { default as EmailIcon } from "./email.svg"
export { default as AutoFormAIIcon } from "./autoformai.svg"
export { default as ChromeIcon } from "./chrome.svg"